SELECT BOOK.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(BOOK_SALES.SALES * BOOK.PRICE) TOTAL_SALES
FROM BOOK JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
JOIN BOOK_SALES ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY BOOK.AUTHOR_ID, AUTHOR.AUTHOR_NAME, BOOK.CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;