SELECT II.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO II JOIN ITEM_TREE IT
ON II.ITEM_ID = IT.ITEM_ID
WHERE II.ITEM_ID NOT IN
(   SELECT PARENT_ITEM_ID
    FROM ITEM_TREE IT
    GROUP BY PARENT_ITEM_ID
    HAVING IT.ITEM_ID = PARENT_ITEM_ID
)
ORDER BY ITEM_ID DESC;