SELECT ID, COALESCE(JT.CNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA LEFT JOIN(SELECT PARENT_ID, COUNT(*) AS CNT
                         FROM ECOLI_DATA
                         GROUP BY PARENT_ID
                         HAVING PARENT_ID IS NOT NULL) JT
                         ON ECOLI_DATA.ID = JT.PARENT_ID
ORDER BY ID;