SELECT IT.ITEM_ID, I.ITEM_NAME, RARITY
FROM ITEM_INFO I JOIN ITEM_TREE IT
ON I.ITEM_ID = IT.ITEM_ID
WHERE IT.PARENT_ITEM_ID IN (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY = 'RARE')
ORDER BY IT.ITEM_ID DESC;