SELECT YEAR(A.DIFFERENTIATION_DATE) AS YEAR, ABS(B.MAX_SIZE_OF_COLONY - A.SIZE_OF_COLONY) AS YEAR_DEV, A.ID
FROM ECOLI_DATA A 
JOIN (SELECT YEAR(A.DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE_OF_COLONY
    FROM ECOLI_DATA A
    GROUP BY YEAR(A.DIFFERENTIATION_DATE)) AS B
ON B.YEAR = YEAR(A.DIFFERENTIATION_DATE)
ORDER BY YEAR ASC, YEAR_DEV ASC;